# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd01
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data/data/:/data/db
